# Generated by Django 4.1.7 on 2023-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='comment',
            field=models.CharField(default='not available', max_length=40),
            preserve_default=False,
        ),
    ]
