# Generated by Django 4.1.7 on 2023-03-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.IntegerField()),
                ('stuName', models.CharField(max_length=70)),
                ('stuEmail', models.EmailField(max_length=70)),
                ('stuPass', models.CharField(max_length=70)),
            ],
        ),
    ]
